LeilaoBundle:
    path:      /leilao/passagens/{situation}
    defaults:  { _controller: LeilaoBundle:Leilao:index, situation:open }

darLanceLeilaoBundle:
    path:      /leilao/darLance/{leilaoId}
    defaults:  { _controller: LeilaoBundle:Leilao:darLance }

leilaoLive:
    path:      /leilao/live
    defaults:  { _controller: LeilaoBundle:Leilao:live }